disabled_rules:
  # - colon
  # - comma
  # - control_statement
  - line_length
  - variable_name
  # - function_parameter_count
  - trailing_whitespace
  - trailing_newline
  # - force_try
opt_in_rules:
  # - empty_count
  - missing_docs
included:
  - RxWorkshop
excluded:
  - Carthage
  - Pods

force_cast: warning
force_try:
  severity: warning
cyclomatic_complexity:
  warning: 10
  error: 30
line_length: 120
type_body_length:
  warning: 300
  error: 400
function_body_length:
  warning: 80
  error: 120
file_length:
  warning: 500
  error: 800
type_name:
  min_length: 2
  max_length:
    warning: 50
    error: 60
  excluded: iPhone
variable_name:
  min_length:
    warning: 1
  excluded:
    - id
    - URL
function_parameter_count:
  warning: 8
  error: 12
